In [ ]:
import math
# Bai 1 :
a = int(input("Nhap vao a "))
b = int(input("Nhap vao b "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

Nhap vao a 2
Nhap vao b 5
7
-3
10
0.4


In [ ]:
# Bai 2 :
a = str(input("Nhap vao a "))
print(a[2:5])


Nhap vao a Hello World
llo


In [ ]:
from os import replace
# Bai 3 :
a = str(input("Nhap vao a:          "))
a= a.strip()
# Dang Hoa Va Dang Thuong
upper_a=a.upper()
lower_a=a.lower()

print(upper_a)
print(lower_a)
# Xoa Khoang Trang
print(" Xoa Khoang Trang:",a)
#Thay chu
replace = a.replace('H','J')
print(replace)

Nhap vao a:          Hello World
HELLO WORLD
hello world
 Xoa Khoang Trang: Hello World
Jello World


In [ ]:
# Bai 4 :
a = str(input("Nhap vao a: "))
b = str(input("Nhap vao b: "))


if a > b:
    print("a",a)
elif a != b:
    print("b",)
else:
    print("a bằng b")

Nhap vao a: hello
Nhap vao b: hi
b hi


In [ ]:
# Bai 5
a = str(input("Nhap vao a: "))
b = str(input("Nhap vao b: "))
if a == b :
  print ("Yes")
elif a != b :
  print ("No")

Nhap vao a: hi
Nhap vao b: haa
No


In [ ]:
# Bai 6
a = str(input("Nhap vao a: "))
b = str(input("Nhap vao b: "))
if a == b:
  print('1')
elif a > b:
  print('2')
else:
  print('3')

Nhap vao a: 1
Nhap vao b: 2
3


In [ ]:
# Bai 7
a = int(input("Nhap vao a: "))
b = int(input("Nhap vao b: "))
d = int(input("Nhap vao c: "))
if a == b or b == d :
  print("Hello World")
else:
  print('0')

Nhap vao a: 2
Nhap vao b: 2
Nhap vao c: 2
Hello World


In [ ]:
# Bai 8
a = int(input("Nhap vao a: "))
b = int(input("Nhap vao b: "))
c = int(input("Nhap vao c: "))
d = int(input("Nhap vao d: "))
if a == b or c == d :
  print("Hello World")
else:
  print('0')

Nhap vao a: 1
Nhap vao b: 2
Nhap vao c: 3
Nhap vao d: 4
0


In [ ]:
# Bai 9
a = int(input("Nhap vao a: "))
b = int(input("Nhap vao b: "))
if a > b :
  print ("Yes")
else:
  print ("No")

Nhap vao a: 2 
Nhap vao b: 3
No


In [ ]:
# Bai 10
a = int(input("Nhap vao a: "))
b = int(input("Nhap vao b: "))
print("A") if a > b else print("=") if a == b else print("B")

Nhap vao a: 2
Nhap vao b: 3
B


In [ ]:
# Bai 11
import numpy as np
a = int(input("Nhap vao a: "))
for i in range(a + 1):
  print(i)
a = np.arange(a + 1)
print(a)
a = a[a % 2 == 0]
print("Cac so chan chan la ", a)

Nhap vao a: 20
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Cac so chan chan la  [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# Bai 12:
a = int(input("Nhap vao a: "))
sum = 0
for i in range(a + 1):
  if i % 3 == 0 or i % 5 == 0:
    sum += i
print("Tong cac so tu 0 den", a, "la boi cua 3 hoac 5 la:", sum)

Nhap vao a: 999
Tong cac so tu 0 den 999 la boi cua 3 hoac 5 la: 233168


In [ ]:
# Bai 13
input_int = input("Nhap vao cac so (mang a): ")
a = [int(x) for x in input_int.split()]
print("Mang a:", a)

input_int = input("Nhap vao cac so (mang b): ")
b = [int(x) for x in input_int.split()]
print("Mang b:", b)

c = []
min_len = len(a) if len(a) < len(b) else len(b)

# Cộng các phần tử tương ứng
for i in range(min_len):
    c.append(a[i] + b[i])

# Thêm phần tử còn lại
if len(a) > len(b):
    c.extend(a[min_len:])
else:
    c.extend(b[min_len:])

print("Mang ket qua:", c)

Nhap vao cac so (mang a): 1 2 3 4 
Mang a: [1, 2, 3, 4]
Nhap vao cac so (mang b): 4 5 6 
Mang b: [4, 5, 6]
Mang ket qua: [5, 7, 9, 4]


In [ ]:
# Bai 14
import numpy as np

m = int(input("Nhap so dong m: "))
n = int(input("Nhap so cot n: "))

a = list(map(int, input(f"Nhap mang a ({m*n} phan tu): ").split()))
a = np.array(a).reshape(m, n)

print("Mang a:\n", a)
# Tao mang a chua cac so ngau nhien
c = np.random.randint(0, 10, size=(m, n))
print("Mang c:\n", c)
# Xuat cac phan tu thuoc dong k
k = int(input("Nhap dong k: "))
print("Cac phan tu thuoc dong", k, "la:", a[k, :])
# Xuat cac phan tu thuoc cot k
k = int(input("Nhap cot k: "))
print("Cac phan tu thuoc cot", k, "la:", a[:, k])
# Tim dong co tong lon nhat 45
max_sum = 0
max_sum_row = 0

for i in range(m):
    row_sum = np.sum(a[i, :])
    if row_sum > max_sum:
        max_sum = row_sum
        max_sum_row = i

print("Dong co tong lon nhat la dong :", max_sum_row)
print("Tong lon nhat la:", max_sum)
# Tim cot co tich nho nhat

min_tich = float('inf')
min_tich_col = 0

for i in range(n):
    tich = np.prod(a[:, i])

    if tich < min_tich:
        min_tich = tich
        min_tich_col = i

print("Cot co tich nho nhat la cot so :", min_tich_col)
print("Tich nho nhat la:", min_tich)
# Xuat ra cac phan tu thuoc dong chan va cot le trong a
print("Cac phan tu thuoc dong chan va cot le trong a:")
for i in range(0, m, 2):
    for j in range(1, n, 2):
        print(a[i, j], end=" ")
    print()
# Tinh trung binh cong cac phan tu chan thuoc dong le cua a
print("Trung binh cong cac phan tu chan thuoc dong le cua a:")
sum = 0
for i in range(1, m, 2):3
for j in range(n):
      sum = np.sum(a[i, :])
      print(sum/n)
# Tinh trung binh cong cac phan tu thuoc bien
sum = 0
sum += a[0, 0]
sum += a[0, n-1]
sum += a[m-1, 0]
sum += a[m-1, n-1]
print("Trung binh cong cac phan tu thuoc bien:",sum/(4))
# Tinh trung binh cong cac phan tu khong thuoc bien la
sum = 0
for i in range(1, m-1):
    for j in range(1, n-1):
        sum += a[i][j]
    print("Trung binh cong cac phan tu khong thuoc bien la :", sum / ((m-2)*(n-2)))


Nhap so dong m: 2
Nhap so cot n: 3
Nhap mang a (6 phan tu): 10 20 30 44 55 66 
Mang a:
 [[10 20 30]
 [44 55 66]]
Mang c:
 [[6 8 8]
 [8 1 2]]
Nhap dong k: 0
Cac phan tu thuoc dong 0 la: [10 20 30]
Nhap cot k: 1
Cac phan tu thuoc cot 1 la: [20 55]
Dong co tong lon nhat la dong : 1
Tong lon nhat la: 165
Cot co tich nho nhat la cot so : 0
Tich nho nhat la: 440
Cac phan tu thuoc dong chan va cot le trong a:
20 
Trung binh cong cac phan tu chan thuoc dong le cua a:
55.0
55.0
55.0
Trung binh cong cac phan tu thuoc bien: 37.5


In [ ]:
# Bai 15
class SinhVien:
    def __init__(self, maSV, ten, namSinh, diemTB):
        self.maSV = maSV
        self.ten = ten
        self.namSinh = namSinh
        self.diemTB = diemTB


# Cho một mảng có n sinh viên
n = int(input("Nhap so sinh vien: "))
ds = []

for i in range(n):
    print("Nhap sinh vien:", i+1)

    maSV = input("Mã SV: ")
    ten = input("Tên: ")
    namSinh = int(input("Năm sinh: "))
    diemTB = float(input("Điểm TB: "))

    sv = SinhVien(maSV, ten, namSinh, diemTB)
    ds.append(sv)


# c. Sinh viên lên lớp
def len_lop(ds):
    dem = 0
    for sv in ds:
        if sv.diemTB >= 5:
            dem += 1
    return dem

print("Số SV đủ điều kiện lên lớp:", len_lop(ds))


# d. Sinh viên đủ 20 tuổi
from datetime import datetime
nam_hien_tai = datetime.now().year

print("Sinh viên đủ 20 tuổi:")
for sv in ds:
    if nam_hien_tai - sv.namSinh >= 20:
        print(sv.maSV, sv.ten, sv.namSinh, sv.diemTB)


# e. Sinh viên hệ DH
def dem_DH(ds):
    dem = 0
    for sv in ds:
        if sv.maSV[2:4] == "DH":
            dem += 1
    return dem

print("Số sinh viên hệ đại học:", dem_DH(ds))


# f. Sinh viên tên Lan
def dem_Lan(ds):
    dem = 0
    for sv in ds:
        if "Lan" in sv.ten:
            dem += 1
    return dem

print("Số sinh viên tên Lan:", dem_Lan(ds))


# g. Sinh viên họ Phan
def dem_Phan(ds):
    dem = 0
    for sv in ds:
        if sv.ten.startswith("Phan"):
            dem += 1
    return dem

print("Số sinh viên họ Phan:", dem_Phan(ds))

Nhap so sinh vien: 3
Nhap sinh vien: 1
Mã SV: 021213
Tên: Phan Huong
Năm sinh: 2000
Điểm TB: 7.0
Nhap sinh vien: 2
Mã SV: 023243
Tên: Lan
Năm sinh: 2000
Điểm TB: 7.0
Nhap sinh vien: 3
Mã SV: 12324
Tên: Huy
Năm sinh: 3000
Điểm TB: 3.0
Số SV đủ điều kiện lên lớp: 2
Sinh viên đủ 20 tuổi:
021213 Phan Huong 2000 7.0
023243 Lan 2000 7.0
Số sinh viên hệ đại học: 0
Số sinh viên tên Lan: 1
Số sinh viên họ Phan: 1
